branch-defaults:
  master:
    environment: rexler-dev
    group_suffix: null
environment-defaults:
  rexler-dev:
    branch: master
    repository: rexler
global:
  application_name: rexler
  branch: master
  default_ec2_keyname: aws-rexler
  default_platform: Python 3.4
  default_region: us-east-1
  profile: eb-cli
  repository: rexler
  sc: git
