# dateSite/urls.py
from django.conf.urls import url
from . import views
from .autocomplete import OccupationAutocomplete, CountryAutocomplete
from django.contrib.auth.decorators import login_required
from allauth.account.views import LoginView

# We are adding a URL called /home
app_name = 'dateSite'
urlpatterns = [
    url(r'^$',
        login_required(views.Index.as_view()),
        name='main'),
    url(r'^login/',
        views.LoginView.as_view(),
        name='login',
        kwargs={'redirect_authenticated_user': True}),
    url(r'^manager/',
        login_required(views.Manager.as_view()),
        name='manager'),
    url(r'^logout/',
        login_required(views.LogoutView.as_view()),
        name='logout'),
    url(r'^password/reset/',
        views.PasswordResetView.as_view(),
        name='password'),
    url(r'^signup/',
        views.SignupView.as_view(),
        name='signup'),
    url(r'^profile/(?P<slug>\w+)/$',
        login_required(views.ProfileView.as_view()),
        name='profile'),
    url(r'^profile/edit/(?P<slug>[\-\w]+)/$',
        login_required(views.UpdateProfileView.as_view()),
        name='edit_profile'),
    url(r'^alerts/',
        login_required(views.AlertsView.as_view()),
        name='alerts'),
    url(r'^ajax/clients/',
        login_required(views.ajax_clients),
        name='client_list'),
    url(r'^ajax/infogirl/',
        login_required(views.ajax_info_complete_client),
        name='info_complete_client'),
    url(r'^ajax/feeling/$',
        login_required(views.ajax_feeling),
        name='change_feeling'),
    url(r'^ajax/profile/picture$',
        login_required(views.ajax_profile_picture),
        name='profile_picture'),
    url(r'^ajax/get/album$',
        login_required(views.ajax_get_album),
        name='get_album'),
    url(r'^ajax/get/albums$',
        login_required(views.ajax_get_albums),
        name='get_albums'),
    url(r'^ajax/add/private',
        login_required(views.ajax_add_private_album),
        name='add_private_album'),
    url(r'^ajax/delete/album',
        login_required(views.ajax_delete_album),
        name='delete_album'),
    url(r'^ajax/create/album',
        login_required(views.ajax_create_album),
        name='create_album'),
    url(r'^ajax/messages/$',
        login_required(views.ajax_room),
        name='my_room'),
    url(r'^ajax/leaveconversation/$',
        login_required(views.leave_conversation),
        name='leaveconversation'),
    url(r'^ajax/notifications/$',
        login_required(views.ajax_notifications),
        name='notifications'),
    url(r'^ajax/qty/noti/$',
        login_required(views.ajax_qtynoti),
        name='qty_notifications'),
    url(r'^ajax/update/noti/$',
        login_required(views.ajax_readnoti),
        name='read_notifications'),
    url(r'^ajax/checkReadMessage/$',
        login_required(views.ajax_check_readmessage),
        name='read_message'),
    url(r'^ajax/list_chat/$',
        login_required(views.ajax_list_chat),
        name='list_chat'),
    url(r'^online/',
        login_required(views.OnlineMembers.as_view()),
        name='online_members'),
    # autocomplete fields
    url(r'^occupation-autocomplete/$',
        OccupationAutocomplete.as_view(),
        name='occupation_autocomplete'),
    url(r'^country-autocomplete/$',
        CountryAutocomplete.as_view(),
        name='country_autocomplete'),
    # info views
    url(r'^about',
        views.about_view,
        name='about'),
    url(r'^faq',
        views.faq_view,
        name='faq'),
    url(r'^terms',
        views.terms_view,
        name='terms'),
    url(r'^policy',
        views.privacy_view,
        name='policy'),
    url(r'^securely',
        views.securely_view,
        name='securely'),
    url(r'^contactus',
        views.contact_view,
        name='contactus'),
]
